# Generated by Django 4.2.16 on 2026-02-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyOperatingHours',
        ),
    ]
